project_id = "ddvfcymvhnlvqcbhozpc"

[functions.verify-certificate]
verify_jwt = false

[functions.scan-google-drive]
verify_jwt = false

[functions.sync-courses]
verify_jwt = false

[functions.auto-scan-courses]
verify_jwt = false