-- SQL to restore missing tags for courses
UPDATE public.courses SET tags = ARRAY['corona', 'rendering', 'architecture', '3ds max']::text[] WHERE slug = 'corona-architecture-rendering-scratch';
UPDATE public.courses SET tags = ARRAY['animation', 'corona', 'vray', '3ds max', 'walkthrough']::text[] WHERE slug = 'animation-corona-vray-3ds-max';
UPDATE public.courses SET tags = ARRAY['corona', 'lighting', 'architecture', '3ds max']::text[] WHERE slug = 'corona-9-architectural-lighting-workshop';
UPDATE public.courses SET tags = ARRAY['interior', 'lighting', 'corona', 'vray']::text[] WHERE slug = 'interior-lighting-corona-vray-zero-advanced';
UPDATE public.courses SET tags = ARRAY['vray', 'lighting', 'advanced', 'photorealistic']::text[] WHERE slug = 'lighting-mastery-vray-6';
UPDATE public.courses SET tags = ARRAY['3ds max', 'modeling', 'beginner', 'efficiency']::text[] WHERE slug = '3d-modeling-3ds-max-quickest-way';
UPDATE public.courses SET tags = ARRAY['3ds max', 'vray', 'architecture', 'complete course']::text[] WHERE slug = '3ds-max-vray-zero-architectural-masterpiece';
UPDATE public.courses SET tags = ARRAY['3ds max', 'interior design', 'animation', 'walkthrough']::text[] WHERE slug = '3ds-max-interior-design-animation';
UPDATE public.courses SET tags = ARRAY['3ds max', 'vray', 'vantage', 'exterior', 'modern']::text[] WHERE slug = 'modern-exterior-archviz-3ds-max-vray-vantage';
UPDATE public.courses SET tags = ARRAY['3ds max', 'corona', 'interior', 'professional']::text[] WHERE slug = 'professional-interior-visualization-3ds-max-corona';
UPDATE public.courses SET tags = ARRAY['3ds max', 'vray', 'daylight', 'interior']::text[] WHERE slug = '3ds-max-vray-interior-daylight-handbook';
UPDATE public.courses SET tags = ARRAY['revit', 'bim', 'beginner', 'architecture']::text[] WHERE slug = 'master-revit-beginner-intermediate-bim';
UPDATE public.courses SET tags = ARRAY['revit', 'villa', 'project', 'architecture']::text[] WHERE slug = 'revit-architectural-work-villa-project';
UPDATE public.courses SET tags = ARRAY['revit', 'landscape', 'bim', 'architecture']::text[] WHERE slug = 'revit-landscape-architecture-bim';
UPDATE public.courses SET tags = ARRAY['revit', 'complete', 'beginner', 'advanced']::text[] WHERE slug = 'revit-2023-complete-beginner-advanced';
UPDATE public.courses SET tags = ARRAY['revit', 'bim', 'masterclass', 'rendering']::text[] WHERE slug = 'bim-revit-masterclass-project-modeling-rendering';
UPDATE public.courses SET tags = ARRAY['revit', 'kitchen', 'interior design']::text[] WHERE slug = 'mastering-kitchen-interior-design-revit';
UPDATE public.courses SET tags = ARRAY['revit', 'documentation', 'detailing', 'sheets']::text[] WHERE slug = 'revit-2025-detailing-sheets-documentation';
UPDATE public.courses SET tags = ARRAY['revit', 'site', 'context', 'topography']::text[] WHERE slug = 'revit-site-context-modeling';
UPDATE public.courses SET tags = ARRAY['revit', 'civil3d', 'landscape', 'bim']::text[] WHERE slug = 'revit-civil3d-landscape-bim-workflow';
UPDATE public.courses SET tags = ARRAY['revit', 'industrial', 'mep', 'structural']::text[] WHERE slug = 'revit-industrial-office-interior-structural-mep';
UPDATE public.courses SET tags = ARRAY['revit', 'interior design', '2026', 'rendering']::text[] WHERE slug = 'revit-2026-interior-design-modeling-rendering';
UPDATE public.courses SET tags = ARRAY['revit', 'architecture', 'professional', 'bim']::text[] WHERE slug = 'revit-architecture-mastery-architects-bim';
UPDATE public.courses SET tags = ARRAY['revit', 'documentation', 'annotation', 'bim']::text[] WHERE slug = 'bim-documentation-annotation-revit';
UPDATE public.courses SET tags = ARRAY['revit', 'architecture', 'structure', 'interior']::text[] WHERE slug = 'revit-architecture-structure-interior-2024';
UPDATE public.courses SET tags = ARRAY['revit', 'autocad', 'architecture', 'master course']::text[] WHERE slug = 'architecture-master-autocad-revit';
UPDATE public.courses SET tags = ARRAY['enscape', 'revit', 'visualization', 'real-time']::text[] WHERE slug = 'enscape-revit-architectural-visualization';
UPDATE public.courses SET tags = ARRAY['sketchup', 'advanced', 'architecture']::text[] WHERE slug = 'sketchup-advanced-architecture';
UPDATE public.courses SET tags = ARRAY['sketchup', 'vray', 'layout', 'architecture']::text[] WHERE slug = 'master-sketchup-vray-layout-architecture';
UPDATE public.courses SET tags = ARRAY['sketchup', 'buildings', 'interiors', 'furniture']::text[] WHERE slug = 'designing-buildings-interiors-furniture-sketchup';
UPDATE public.courses SET tags = ARRAY['sketchup', 'interior design', 'beginner', 'pro']::text[] WHERE slug = 'basic-advanced-interior-designer-sketchup-pro';
UPDATE public.courses SET tags = ARRAY['sketchup', 'vray', 'interior', 'rendering']::text[] WHERE slug = 'realistic-interior-rendering-sketchup-vray7';
UPDATE public.courses SET tags = ARRAY['sketchup', '2024', 'complete', 'beginner']::text[] WHERE slug = 'sketchup-2024-complete-course';
UPDATE public.courses SET tags = ARRAY['sketchup', 'vray', 'interior', 'visualization']::text[] WHERE slug = 'master-interior-visualization-sketchup-vray';
UPDATE public.courses SET tags = ARRAY['autocad', 'working drawings', 'projects', 'documentation']::text[] WHERE slug = 'mastering-working-drawings-extended-5-projects';
UPDATE public.courses SET tags = ARRAY['autocad', 'working drawings', 'workflow', 'professional']::text[] WHERE slug = 'mastering-working-drawings-real-project-workflow';
UPDATE public.courses SET tags = ARRAY['autocad', 'building design', 'architecture']::text[] WHERE slug = 'architectural-building-design-autocad';
UPDATE public.courses SET tags = ARRAY['autocad', 'sketchup', '2d', '3d', 'working drawings']::text[] WHERE slug = 'complete-2d-3d-working-drawing-autocad-sketchup';
UPDATE public.courses SET tags = ARRAY['autocad', 'sketchup', 'beginner', 'complete']::text[] WHERE slug = 'master-autocad-sketchup-beginner-pro';
UPDATE public.courses SET tags = ARRAY['autocad', 'floor plans', 'elevations', 'architecture']::text[] WHERE slug = 'master-architectural-floor-plans-elevations-autocad';
UPDATE public.courses SET tags = ARRAY['autocad', 'landscape', 'design plan']::text[] WHERE slug = 'master-autocad-landscape-architects';
UPDATE public.courses SET tags = ARRAY['autocad', 'structural', 'detailing']::text[] WHERE slug = 'complete-autocad-structural-detailing';
UPDATE public.courses SET tags = ARRAY['autocad', 'drafting', 'architecture', 'beginner']::text[] WHERE slug = 'architectural-autocad-drafting';
UPDATE public.courses SET tags = ARRAY['autocad', 'structural', 'drafting']::text[] WHERE slug = 'structural-autocad-drafting';
UPDATE public.courses SET tags = ARRAY['lumion', 'resort', 'advanced', 'visualization']::text[] WHERE slug = 'advanced-lumion-resort-workflow';
UPDATE public.courses SET tags = ARRAY['lumion', 'beginner', 'complete']::text[] WHERE slug = 'learning-lumion-12-pro-zero-hero';
UPDATE public.courses SET tags = ARRAY['lumion', 'mastery', 'rendering', 'architecture']::text[] WHERE slug = 'lumion-12-mastery-architectural-rendering-az';
UPDATE public.courses SET tags = ARRAY['twinmotion', '2025', 'photorealistic', 'real-time']::text[] WHERE slug = 'twinmotion-2025-zero-advanced-ultra-realistic';
UPDATE public.courses SET tags = ARRAY['twinmotion', 'real-time', 'visualization']::text[] WHERE slug = 'twinmotion-realtime-3d-rendering-visualization';
UPDATE public.courses SET tags = ARRAY['twinmotion', 'architecture', 'designers']::text[] WHERE slug = 'twinmotion-architectural-designers';
UPDATE public.courses SET tags = ARRAY['d5 render', 'photorealistic', 'architecture', 'real-time']::text[] WHERE slug = 'd5-render-pro-2026-photorealistic-rendering';
UPDATE public.courses SET tags = ARRAY['rhino', 'complete', 'architects', 'designers']::text[] WHERE slug = 'full-rhino-complete-architects-designers';
UPDATE public.courses SET tags = ARRAY['rhino', 'lumion', 'modeling', 'rendering']::text[] WHERE slug = 'rhino-3d-lumion-photorealistic-rendering';
UPDATE public.courses SET tags = ARRAY['rhino', 'crash course', 'beginner', 'quick']::text[] WHERE slug = 'rhino-3d-crash-course-zero-hero';
UPDATE public.courses SET tags = ARRAY['rhino', 'beginner', 'villa', 'project']::text[] WHERE slug = 'rhino-beginners-course-designing-villa';
UPDATE public.courses SET tags = ARRAY['rhino', 'masterclass', 'professional', 'complete']::text[] WHERE slug = 'rhino-3d-masterclass-beginner-professional';
UPDATE public.courses SET tags = ARRAY['rhino', 'exterior', 'visualization', 'advanced']::text[] WHERE slug = 'advanced-exterior-visualization-rhino';
UPDATE public.courses SET tags = ARRAY['drawing', 'sketching', 'conceptual', 'architecture']::text[] WHERE slug = 'architectural-drawing-imagination-conceptualization';
UPDATE public.courses SET tags = ARRAY['sketching', 'hand drawing', 'architecture']::text[] WHERE slug = 'architectural-sketching-thinking-pen-paper';
UPDATE public.courses SET tags = ARRAY['sketching', 'introduction', 'beginner']::text[] WHERE slug = 'introduction-architectural-sketching';
UPDATE public.courses SET tags = ARRAY['reading drawings', 'construction', 'beginner']::text[] WHERE slug = '7-days-mastery-read-architectural-drawings';
UPDATE public.courses SET tags = ARRAY['english', 'communication', 'professional']::text[] WHERE slug = 'architectural-english-design-students-professionals';
UPDATE public.courses SET tags = ARRAY['portfolio', 'indesign', 'professional']::text[] WHERE slug = 'professional-architectural-portfolio-indesign';
UPDATE public.courses SET tags = ARRAY['materials', 'construction', 'architecture']::text[] WHERE slug = 'architectural-materials-masterclass';
UPDATE public.courses SET tags = ARRAY['residential', 'design', 'architecture', 'beginner']::text[] WHERE slug = 'intro-architectural-design-residential-spaces';
UPDATE public.courses SET tags = ARRAY['concept', 'sketching', 'design']::text[] WHERE slug = 'concept-sketching-architecture-design';
UPDATE public.courses SET tags = ARRAY['foundation', 'sketching', 'beginner']::text[] WHERE slug = 'foundation-sketching-architectural-design-part1';
UPDATE public.courses SET tags = ARRAY['diagrams', 'presentation', 'design']::text[] WHERE slug = 'architectural-diagrams-masterclass';
UPDATE public.courses SET tags = ARRAY['design', 'fundamentals', 'architecture']::text[] WHERE slug = 'architectural-design-fundamentals';
UPDATE public.courses SET tags = ARRAY['frank gehry', 'masterclass', 'design philosophy']::text[] WHERE slug = 'frank-gehry-teaches-design-architecture';
UPDATE public.courses SET tags = ARRAY['marker', 'rendering', 'hand drawing']::text[] WHERE slug = 'introduction-marker-rendering-architecture-interiors';
UPDATE public.courses SET tags = ARRAY['construction', 'management', 'engineering']::text[] WHERE slug = 'complete-guide-construction-engineering-management';
UPDATE public.courses SET tags = ARRAY['planning', 'management', 'professional']::text[] WHERE slug = 'master-planner-program-pro';
UPDATE public.courses SET tags = ARRAY['interior design', 'complete', 'beginner']::text[] WHERE slug = 'complete-interior-design-course';
UPDATE public.courses SET tags = ARRAY['interior design', 'living room', 'quick']::text[] WHERE slug = 'interior-design-dream-living-room';
UPDATE public.courses SET tags = ARRAY['interior design', 'fundamentals', '2026']::text[] WHERE slug = 'interior-design-fundamentals-2026-beginner-advanced';
UPDATE public.courses SET tags = ARRAY['photoshop', 'architecture', 'post-production']::text[] WHERE slug = 'photoshop-architects-zero-advanced-masterclass';
UPDATE public.courses SET tags = ARRAY['photoshop', 'post-production', 'presentation']::text[] WHERE slug = 'photoshop-architectural-post-production-presentation';
UPDATE public.courses SET tags = ARRAY['photoshop', 'quick', 'visualization']::text[] WHERE slug = 'photoshop-architectural-visualization-1-hour';
UPDATE public.courses SET tags = ARRAY['drawing', 'photoshop', 'hybrid']::text[] WHERE slug = 'architectural-drawing-paper-photoshop';
UPDATE public.courses SET tags = ARRAY['after effects', 'animation', 'presentation']::text[] WHERE slug = 'architectural-presentation-after-effects-architects';
UPDATE public.courses SET tags = ARRAY['demo', 'test', 'payment']::text[] WHERE slug = 'demo-test-course';
