import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

// All courses from the static data file - comprehensive list
const staticCourses = [
  // Corona & V-Ray Rendering
  { title: 'Corona Renderer Architecture Rendering from Scratch', slug: 'corona-architecture-rendering-scratch', short_description: 'Master Corona Renderer for stunning architectural visualizations from the ground up.', description: 'Dive deep into Corona Renderer and learn to create breathtaking architectural visualizations.', level: 'beginner', duration_hours: 18, total_lessons: 45, price_usd: 89, price_inr: 7499, is_featured: true, is_published: true },
  { title: 'Animation with Corona & V-Ray in 3ds Max', slug: 'animation-corona-vray-3ds-max', short_description: 'Create stunning animated architectural walkthroughs and presentations.', description: 'Learn the art of architectural animation using Corona and V-Ray in 3ds Max.', level: 'intermediate', duration_hours: 14, total_lessons: 32, price_usd: 79, price_inr: 6499, is_featured: false, is_published: true },
  { title: 'Corona 9 + 3ds Max Architectural Lighting Workshop', slug: 'corona-9-architectural-lighting-workshop', short_description: 'Master architectural lighting techniques with Corona 9 and 3ds Max.', description: 'Unlock the secrets of professional architectural lighting.', level: 'intermediate', duration_hours: 12, total_lessons: 28, price_usd: 69, price_inr: 5999, is_featured: true, is_published: true },
  { title: 'Interior Lighting - Corona and V-Ray from Zero to Advanced', slug: 'interior-lighting-corona-vray-zero-advanced', short_description: 'Complete guide to interior lighting with Corona and V-Ray renderers.', description: 'Transform your interior renders with professional lighting techniques.', level: 'beginner', duration_hours: 16, total_lessons: 40, price_usd: 79, price_inr: 6499, is_featured: false, is_published: true },
  { title: 'Lighting Mastery in V-Ray 6', slug: 'lighting-mastery-vray-6', short_description: 'Become a V-Ray 6 lighting expert with advanced techniques.', description: 'Take your V-Ray skills to the next level.', level: 'advanced', duration_hours: 10, total_lessons: 24, price_usd: 89, price_inr: 7499, is_featured: false, is_published: true },
  
  // 3ds Max
  { title: '3D Modeling with 3ds Max - The Quickest Way', slug: '3d-modeling-3ds-max-quickest-way', short_description: 'Fast-track your 3ds Max modeling skills with efficient techniques.', description: 'Learn 3ds Max modeling the smart way.', level: 'beginner', duration_hours: 12, total_lessons: 30, price_usd: 59, price_inr: 4999, is_featured: false, is_published: true },
  { title: '3ds Max + V-Ray: From Zero to Architectural Masterpiece', slug: '3ds-max-vray-zero-architectural-masterpiece', short_description: 'Complete journey from beginner to creating stunning architectural visualizations.', description: 'The ultimate 3ds Max and V-Ray course.', level: 'beginner', duration_hours: 35, total_lessons: 85, price_usd: 149, price_inr: 12499, is_featured: true, is_published: true },
  { title: 'Complete 3ds Max Course for Interior Design with Animation', slug: '3ds-max-interior-design-animation', short_description: 'Master interior design visualization and animation in 3ds Max.', description: 'A comprehensive course designed for interior designers.', level: 'intermediate', duration_hours: 28, total_lessons: 65, price_usd: 129, price_inr: 10999, is_featured: false, is_published: true },
  { title: 'Modern Exterior Arch Viz with 3ds Max, V-Ray & Vantage', slug: 'modern-exterior-archviz-3ds-max-vray-vantage', short_description: 'Create stunning modern exterior visualizations with real-time preview.', description: 'Learn cutting-edge exterior visualization techniques.', level: 'advanced', duration_hours: 20, total_lessons: 48, price_usd: 99, price_inr: 8499, is_featured: true, is_published: true },
  { title: 'Professional Interior Visualization - 3ds Max + Corona', slug: 'professional-interior-visualization-3ds-max-corona', short_description: 'Industry-standard interior visualization workflow with Corona.', description: 'Learn the professional workflow for creating stunning interior visualizations.', level: 'intermediate', duration_hours: 22, total_lessons: 52, price_usd: 109, price_inr: 9499, is_featured: false, is_published: true },
  { title: '3ds Max + V-Ray: Interior Daylight Visualization Handbook', slug: '3ds-max-vray-interior-daylight-handbook', short_description: 'Master natural daylight in interior renders for realistic results.', description: 'Daylight is the foundation of beautiful interior renders.', level: 'intermediate', duration_hours: 10, total_lessons: 25, price_usd: 69, price_inr: 5999, is_featured: false, is_published: true },
  { title: '3ds Max Architectural Modeling Complete Course', slug: '3ds-max-architectural-modeling-complete', short_description: 'Complete 3ds Max course for architectural modeling.', description: 'Learn architectural modeling from scratch to professional level.', level: 'beginner', duration_hours: 24, total_lessons: 60, price_usd: 99, price_inr: 8499, is_featured: false, is_published: true },
  
  // Revit & BIM
  { title: 'Master Autodesk Revit - Beginner to Intermediate with BIM Introduction', slug: 'master-revit-beginner-intermediate-bim', short_description: 'Complete Revit foundation with BIM methodology introduction.', description: 'Start your BIM journey with this comprehensive Revit course.', level: 'beginner', duration_hours: 25, total_lessons: 60, price_usd: 99, price_inr: 8499, is_featured: true, is_published: true },
  { title: 'Revit Architectural Work with Live Villa Project', slug: 'revit-architectural-work-villa-project', short_description: 'Learn Revit through a complete villa design project.', description: 'The best way to learn is by doing.', level: 'intermediate', duration_hours: 20, total_lessons: 48, price_usd: 89, price_inr: 7499, is_featured: false, is_published: true },
  { title: 'Revit Landscape Architecture BIM Techniques', slug: 'revit-landscape-architecture-bim', short_description: 'Specialized Revit workflows for landscape architects.', description: 'Discover how to leverage Revit for landscape architecture projects.', level: 'intermediate', duration_hours: 14, total_lessons: 35, price_usd: 79, price_inr: 6499, is_featured: false, is_published: true },
  { title: 'Revit 2023 Complete Course - Beginner to Advanced', slug: 'revit-2023-complete-beginner-advanced', short_description: 'The most comprehensive Revit course from basics to advanced techniques.', description: 'Everything you need to master Revit in one course.', level: 'beginner', duration_hours: 40, total_lessons: 95, price_usd: 149, price_inr: 12499, is_featured: true, is_published: true },
  { title: 'BIM Revit Masterclass: Complete Project Modeling + Rendering', slug: 'bim-revit-masterclass-project-modeling-rendering', short_description: 'Master BIM workflow from modeling to photorealistic visualization.', description: 'A masterclass that combines BIM modeling expertise with stunning visualization.', level: 'advanced', duration_hours: 32, total_lessons: 75, price_usd: 139, price_inr: 11999, is_featured: false, is_published: true },
  { title: 'Mastering Kitchen Interior Design with Revit', slug: 'mastering-kitchen-interior-design-revit', short_description: 'Specialize in kitchen design using Revit tools.', description: 'Kitchen design requires precision and creativity.', level: 'intermediate', duration_hours: 12, total_lessons: 28, price_usd: 69, price_inr: 5999, is_featured: false, is_published: true },
  { title: 'Revit 2025: Detailing, Sheets & Documentation - Project-Based', slug: 'revit-2025-detailing-sheets-documentation', short_description: 'Master construction documentation with Revit 2025.', description: 'Transform your Revit models into professional construction documents.', level: 'intermediate', duration_hours: 16, total_lessons: 40, price_usd: 79, price_inr: 6499, is_featured: false, is_published: true },
  { title: 'Revit Site and Context Modeling', slug: 'revit-site-context-modeling', short_description: 'Create compelling site plans and context models.', description: 'Learn to model sites, topography, and context in Revit.', level: 'intermediate', duration_hours: 10, total_lessons: 24, price_usd: 59, price_inr: 4999, is_featured: false, is_published: true },
  { title: 'Revit & Civil 3D for Landscape BIM Workflow', slug: 'revit-civil-3d-landscape-bim-workflow', short_description: 'Integrate Revit and Civil 3D for powerful landscape BIM.', description: 'Combine the power of Revit and Civil 3D for landscape architecture.', level: 'advanced', duration_hours: 18, total_lessons: 42, price_usd: 99, price_inr: 8499, is_featured: false, is_published: true },
  { title: 'Revit Industrial Office: Interior Design, Structural and MEP', slug: 'revit-industrial-office-interior-structural-mep', short_description: 'Complete industrial office project with all disciplines.', description: 'Learn multi-discipline Revit workflows for industrial projects.', level: 'advanced', duration_hours: 28, total_lessons: 65, price_usd: 139, price_inr: 11999, is_featured: false, is_published: true },
  { title: 'Revit 2026: Interior Design, Modeling & Rendering from Zero', slug: 'revit-2026-interior-design-modeling-rendering', short_description: 'Latest Revit for complete interior design workflow.', description: 'Start from zero and master interior design in Revit 2026.', level: 'beginner', duration_hours: 22, total_lessons: 50, price_usd: 99, price_inr: 8499, is_featured: false, is_published: true },
  { title: 'Revit Architecture Mastery for Architects and BIM Modelers', slug: 'revit-architecture-mastery-architects-bim-modelers', short_description: 'Professional Revit skills for practicing architects.', description: 'Master Revit as used by professional architects.', level: 'advanced', duration_hours: 35, total_lessons: 80, price_usd: 159, price_inr: 13499, is_featured: false, is_published: true },
  { title: 'BIM Documentation & Annotation in Revit: From Zero to Pro', slug: 'bim-documentation-annotation-revit-zero-pro', short_description: 'Master the art of BIM documentation and annotation.', description: 'Learn professional documentation standards in Revit.', level: 'intermediate', duration_hours: 14, total_lessons: 35, price_usd: 69, price_inr: 5999, is_featured: false, is_published: true },
  { title: 'Revit Architecture Master Class', slug: 'revit-architecture-master-class', short_description: 'Comprehensive Revit architecture masterclass.', description: 'Master Revit Architecture from beginner to advanced level.', level: 'intermediate', duration_hours: 30, total_lessons: 70, price_usd: 129, price_inr: 10999, is_featured: true, is_published: true },
  { title: 'Revit Architecture & Structure with Interior Designing 2024', slug: 'revit-architecture-structure-interior-2024', short_description: 'Combined architectural, structural and interior design in Revit.', description: 'Learn architectural, structural and interior design workflows in Revit.', level: 'intermediate', duration_hours: 28, total_lessons: 65, price_usd: 119, price_inr: 9999, is_featured: false, is_published: true },
  { title: 'Architecture Master Course in AutoCAD and Revit', slug: 'architecture-master-autocad-revit', short_description: 'Master both AutoCAD and Revit for complete architectural workflow.', description: 'Learn to use AutoCAD and Revit together for professional architecture.', level: 'intermediate', duration_hours: 35, total_lessons: 80, price_usd: 149, price_inr: 12499, is_featured: false, is_published: true },
  { title: 'Enscape for Revit: Learn Architectural Visualization', slug: 'enscape-revit-architectural-visualization', short_description: 'Real-time visualization directly from your Revit models.', description: 'Create stunning real-time visualizations with Enscape and Revit.', level: 'intermediate', duration_hours: 10, total_lessons: 25, price_usd: 69, price_inr: 5999, is_featured: false, is_published: true },
  
  // SketchUp
  { title: 'SketchUp Advanced Architecture', slug: 'sketchup-advanced-architecture', short_description: 'Take your SketchUp skills to professional architectural level.', description: 'Advanced SketchUp techniques for architects.', level: 'advanced', duration_hours: 16, total_lessons: 40, price_usd: 89, price_inr: 7499, is_featured: true, is_published: true },
  { title: 'Master SketchUp, V-Ray and LayOut - Complete Architecture', slug: 'master-sketchup-vray-layout-architecture', short_description: 'Complete architectural workflow from sketch to presentation.', description: 'Master SketchUp, V-Ray and LayOut for complete architecture workflow.', level: 'intermediate', duration_hours: 32, total_lessons: 78, price_usd: 139, price_inr: 11999, is_featured: true, is_published: true },
  { title: 'Designing Buildings, Interiors and Furniture with SketchUp', slug: 'designing-buildings-interiors-furniture-sketchup', short_description: 'From architecture to furniture design - all in SketchUp.', description: 'Learn to design buildings, interiors, and furniture with SketchUp.', level: 'intermediate', duration_hours: 20, total_lessons: 48, price_usd: 89, price_inr: 7499, is_featured: false, is_published: true },
  { title: 'From Basic to Advanced Interior Designer Using SketchUp Pro', slug: 'basic-advanced-interior-designer-sketchup-pro', short_description: 'Complete interior design journey with SketchUp Pro.', description: 'Become an interior design professional using SketchUp Pro.', level: 'beginner', duration_hours: 24, total_lessons: 58, price_usd: 99, price_inr: 8499, is_featured: false, is_published: true },
  { title: 'Realistic Interior Rendering with SketchUp V-Ray 7', slug: 'realistic-interior-rendering-sketchup-vray7', short_description: 'Create stunning photorealistic interiors with V-Ray 7.', description: 'Master V-Ray 7 for SketchUp to create photorealistic interior renders.', level: 'intermediate', duration_hours: 14, total_lessons: 35, price_usd: 79, price_inr: 6499, is_featured: false, is_published: true },
  { title: 'SketchUp 2024 Complete Course', slug: 'sketchup-2024-complete-course', short_description: 'Learn all of SketchUp 2024 features from scratch.', description: 'Complete SketchUp 2024 training from basics to advanced.', level: 'beginner', duration_hours: 18, total_lessons: 45, price_usd: 79, price_inr: 6499, is_featured: false, is_published: true },
  { title: 'Master Interior Visualization with SketchUp and V-Ray', slug: 'master-interior-visualization-sketchup-vray', short_description: 'Professional interior visualization workflow.', description: 'Create professional interior visualizations with SketchUp and V-Ray.', level: 'intermediate', duration_hours: 20, total_lessons: 50, price_usd: 99, price_inr: 8499, is_featured: false, is_published: true },
  { title: 'SketchUp Pro 2024: Complete Architecture Course', slug: 'sketchup-pro-2024-complete-architecture', short_description: 'Master SketchUp Pro for architectural design and visualization.', description: 'Complete SketchUp course for architects.', level: 'beginner', duration_hours: 20, total_lessons: 50, price_usd: 79, price_inr: 6499, is_featured: true, is_published: true },
  { title: 'V-Ray for SketchUp: Photorealistic Rendering Mastery', slug: 'vray-sketchup-photorealistic-rendering-mastery', short_description: 'Create stunning photorealistic renders with V-Ray for SketchUp.', description: 'Master V-Ray rendering in SketchUp.', level: 'intermediate', duration_hours: 14, total_lessons: 35, price_usd: 89, price_inr: 7499, is_featured: false, is_published: true },
  { title: 'SketchUp for Interior Design: Complete Workflow', slug: 'sketchup-interior-design-complete-workflow', short_description: 'Interior design workflow from concept to visualization.', description: 'Learn the complete interior design workflow in SketchUp.', level: 'intermediate', duration_hours: 16, total_lessons: 40, price_usd: 79, price_inr: 6499, is_featured: false, is_published: true },
  { title: 'SketchUp + Enscape: Real-time Visualization', slug: 'sketchup-enscape-real-time-visualization', short_description: 'Create stunning real-time renders with SketchUp and Enscape.', description: 'Master real-time visualization with Enscape.', level: 'intermediate', duration_hours: 10, total_lessons: 25, price_usd: 69, price_inr: 5999, is_featured: false, is_published: true },
  
  // AutoCAD
  { title: 'AutoCAD 2024: Complete 2D & 3D Drafting Course', slug: 'autocad-2024-complete-2d-3d-drafting', short_description: 'Master AutoCAD for professional drafting and design.', description: 'Complete AutoCAD training from basics to advanced.', level: 'beginner', duration_hours: 25, total_lessons: 60, price_usd: 89, price_inr: 7499, is_featured: true, is_published: true },
  { title: 'AutoCAD Architecture: Professional Building Documentation', slug: 'autocad-architecture-professional-building-documentation', short_description: 'Specialized AutoCAD skills for architectural documentation.', description: 'Learn architectural drafting standards in AutoCAD.', level: 'intermediate', duration_hours: 18, total_lessons: 45, price_usd: 79, price_inr: 6499, is_featured: false, is_published: true },
  { title: '7 Days Mastery Course to Read Architectural Drawings', slug: '7-days-mastery-read-architectural-drawings', short_description: 'Learn to read and understand architectural drawings quickly.', description: 'Fast-track your drawing reading skills.', level: 'beginner', duration_hours: 7, total_lessons: 21, price_usd: 49, price_inr: 3999, is_featured: false, is_published: true },
  { title: 'Mastering Working Drawings - Extended Version with 5 Projects Including Interiors', slug: 'mastering-working-drawings-extended-5-projects', short_description: 'Comprehensive working drawing skills with 5 real projects.', description: 'Master working drawings through hands-on practice with 5 complete projects.', level: 'intermediate', duration_hours: 36, total_lessons: 85, price_usd: 139, price_inr: 11999, is_featured: true, is_published: true },
  { title: 'Mastering Working Drawings with Real Project Workflow', slug: 'mastering-working-drawings-real-project-workflow', short_description: 'Learn working drawings the way professionals do.', description: 'Experience real office workflows for creating working drawings.', level: 'intermediate', duration_hours: 20, total_lessons: 48, price_usd: 89, price_inr: 7499, is_featured: false, is_published: true },
  { title: 'Architectural Project Building Design with AutoCAD', slug: 'architectural-building-design-autocad', short_description: 'Complete building design documentation in AutoCAD.', description: 'Design and document complete buildings using AutoCAD.', level: 'intermediate', duration_hours: 24, total_lessons: 60, price_usd: 99, price_inr: 8499, is_featured: false, is_published: true },
  { title: 'Complete 2D and 3D Working Drawing - AutoCAD & SketchUp Pro', slug: 'complete-2d-3d-working-drawing-autocad-sketchup', short_description: 'Combine AutoCAD 2D and SketchUp 3D for complete documentation.', description: 'Master the powerful combination of AutoCAD for 2D and SketchUp for 3D.', level: 'intermediate', duration_hours: 28, total_lessons: 68, price_usd: 119, price_inr: 9999, is_featured: false, is_published: true },
  { title: 'Master Course: AutoCAD & SketchUp from Beginner to Pro', slug: 'master-autocad-sketchup-beginner-pro', short_description: 'Master both AutoCAD and SketchUp from scratch.', description: 'Two essential design tools in one comprehensive course.', level: 'beginner', duration_hours: 40, total_lessons: 95, price_usd: 149, price_inr: 12499, is_featured: true, is_published: true },
  { title: 'Master Architectural Floor Plans & Elevations in AutoCAD', slug: 'master-architectural-floor-plans-elevations-autocad', short_description: 'Perfect your floor plans and elevations in AutoCAD.', description: 'Create professional floor plans and elevations with proper annotation.', level: 'beginner', duration_hours: 14, total_lessons: 35, price_usd: 69, price_inr: 5999, is_featured: false, is_published: true },
  { title: 'Master AutoCAD for Landscape Architects: Sketch to Design Plan', slug: 'master-autocad-landscape-architects', short_description: 'AutoCAD workflows specifically for landscape design.', description: 'Tailored for landscape architects with plant symbols and irrigation plans.', level: 'intermediate', duration_hours: 16, total_lessons: 40, price_usd: 79, price_inr: 6499, is_featured: false, is_published: true },
  { title: 'Complete AutoCAD Structural Detailing Course', slug: 'complete-autocad-structural-detailing', short_description: 'Master structural detailing and documentation.', description: 'Essential for structural engineers and detailers.', level: 'intermediate', duration_hours: 18, total_lessons: 45, price_usd: 89, price_inr: 7499, is_featured: false, is_published: true },
  { title: 'Architectural AutoCAD Drafting', slug: 'architectural-autocad-drafting', short_description: 'Essential drafting skills for architectural professionals.', description: 'Build a solid foundation in architectural drafting.', level: 'beginner', duration_hours: 12, total_lessons: 30, price_usd: 59, price_inr: 4999, is_featured: false, is_published: true },
  { title: 'Structural AutoCAD Drafting', slug: 'structural-autocad-drafting', short_description: 'Specialized drafting for structural engineering.', description: 'Learn structural drafting techniques in AutoCAD.', level: 'intermediate', duration_hours: 14, total_lessons: 35, price_usd: 69, price_inr: 5999, is_featured: false, is_published: true },
  
  // Visualization Tools
  { title: 'Advanced Lumion Resort Workflow', slug: 'advanced-lumion-resort-workflow', short_description: 'Create stunning resort visualizations with Lumion.', description: 'Master resort and hospitality visualization in Lumion.', level: 'advanced', duration_hours: 16, total_lessons: 40, price_usd: 89, price_inr: 7499, is_featured: true, is_published: true },
  { title: 'Learning Lumion 12.5 Pro from Zero to Hero', slug: 'learning-lumion-12-pro-zero-hero', short_description: 'Complete Lumion 12.5 Pro mastery from scratch.', description: 'Start from zero and become a Lumion hero.', level: 'beginner', duration_hours: 20, total_lessons: 50, price_usd: 89, price_inr: 7499, is_featured: false, is_published: true },
  { title: 'Lumion 12 Mastery: Architectural Rendering A-Z', slug: 'lumion-12-mastery-architectural-rendering-az', short_description: 'Complete A to Z guide for architectural rendering in Lumion.', description: 'Everything about Lumion 12 for architectural visualization.', level: 'intermediate', duration_hours: 24, total_lessons: 60, price_usd: 99, price_inr: 8499, is_featured: false, is_published: true },
  { title: 'Lumion 12: Complete Architectural Visualization', slug: 'lumion-12-complete-architectural-visualization', short_description: 'Create stunning animations and renders with Lumion 12.', description: 'Master Lumion for architectural visualization.', level: 'beginner', duration_hours: 16, total_lessons: 40, price_usd: 89, price_inr: 7499, is_featured: true, is_published: true },
  { title: 'Twinmotion 2025: From Zero to Advanced Level - Ultra Realistic', slug: 'twinmotion-2025-zero-advanced-ultra-realistic', short_description: 'Master Twinmotion 2025 for photorealistic real-time visualization.', description: 'Create ultra-realistic renders with Twinmotion 2025.', level: 'beginner', duration_hours: 22, total_lessons: 55, price_usd: 99, price_inr: 8499, is_featured: true, is_published: true },
  { title: 'Twinmotion Real-Time 3D Rendering Visualization', slug: 'twinmotion-realtime-3d-rendering-visualization', short_description: 'Real-time visualization fundamentals with Twinmotion.', description: 'Learn real-time visualization with Twinmotion.', level: 'beginner', duration_hours: 14, total_lessons: 35, price_usd: 69, price_inr: 5999, is_featured: false, is_published: true },
  { title: 'Twinmotion for Architectural Designers', slug: 'twinmotion-architectural-designers', short_description: 'Twinmotion workflows tailored for architects.', description: 'Learn Twinmotion from an architect perspective.', level: 'intermediate', duration_hours: 12, total_lessons: 30, price_usd: 69, price_inr: 5999, is_featured: false, is_published: true },
  { title: 'Comprehensive Twinmotion 2025 From Zero to Advance', slug: 'comprehensive-twinmotion-2025-zero-advance', short_description: 'Complete Twinmotion 2025 course from basics to advanced.', description: 'Master Twinmotion 2025 with comprehensive training.', level: 'beginner', duration_hours: 20, total_lessons: 48, price_usd: 89, price_inr: 7499, is_featured: false, is_published: true },
  { title: 'Twinmotion 2024: Real-time Visualization from Revit', slug: 'twinmotion-2024-real-time-visualization-revit', short_description: 'Create immersive experiences with Twinmotion and Revit.', description: 'Learn Twinmotion for architectural visualization.', level: 'intermediate', duration_hours: 12, total_lessons: 30, price_usd: 79, price_inr: 6499, is_featured: false, is_published: true },
  { title: 'D5 Render Pro 2026: Architectural Photorealistic Rendering', slug: 'd5-render-pro-2026-photorealistic-rendering', short_description: 'Master D5 Render for stunning photorealistic architecture.', description: 'Create photorealistic renders with D5 Render Pro 2026.', level: 'intermediate', duration_hours: 16, total_lessons: 40, price_usd: 89, price_inr: 7499, is_featured: true, is_published: true },
  { title: 'D5 Render: Next-Gen Real-time Rendering', slug: 'd5-render-next-gen-real-time-rendering', short_description: 'Master D5 Render for stunning real-time visualizations.', description: 'Learn D5 Render from basics to advanced.', level: 'intermediate', duration_hours: 10, total_lessons: 25, price_usd: 69, price_inr: 5999, is_featured: false, is_published: true },
  { title: 'Enscape Complete Course: Real-time for Revit & SketchUp', slug: 'enscape-complete-course-real-time-revit-sketchup', short_description: 'Master Enscape for Revit and SketchUp visualization.', description: 'Complete Enscape training for real-time rendering.', level: 'intermediate', duration_hours: 12, total_lessons: 28, price_usd: 79, price_inr: 6499, is_featured: false, is_published: true },
  
  // Rhino 3D
  { title: 'Full Rhino: A Complete Course for Architects and Designers', slug: 'full-rhino-complete-architects-designers', short_description: 'Comprehensive Rhino mastery for design professionals.', description: 'Master Rhino for architectural design.', level: 'beginner', duration_hours: 28, total_lessons: 70, price_usd: 119, price_inr: 9999, is_featured: true, is_published: true },
  { title: 'Rhino 3D Modeling + Lumion Photorealistic Rendering', slug: 'rhino-3d-lumion-photorealistic-rendering', short_description: 'Combine Rhino modeling with Lumion visualization.', description: 'The perfect pairing for organic architecture.', level: 'intermediate', duration_hours: 20, total_lessons: 50, price_usd: 99, price_inr: 8499, is_featured: false, is_published: true },
  { title: 'Rhino 3D Crash Course: Zero to Hero', slug: 'rhino-3d-crash-course-zero-hero', short_description: 'Fast-track your Rhino skills in record time.', description: 'Learn Rhino quickly without sacrificing depth.', level: 'beginner', duration_hours: 10, total_lessons: 25, price_usd: 59, price_inr: 4999, is_featured: false, is_published: true },
  { title: 'Rhino Beginners Course: Designing a Villa', slug: 'rhino-beginners-course-designing-villa', short_description: 'Learn Rhino by designing a complete villa project.', description: 'Project-based learning with a villa design.', level: 'beginner', duration_hours: 16, total_lessons: 40, price_usd: 79, price_inr: 6499, is_featured: false, is_published: true },
  { title: 'Rhino 3D Masterclass: Go from Beginner to Professional', slug: 'rhino-3d-masterclass-beginner-professional', short_description: 'Complete Rhino journey from basics to professional level.', description: 'The ultimate Rhino learning experience.', level: 'beginner', duration_hours: 35, total_lessons: 85, price_usd: 149, price_inr: 12499, is_featured: true, is_published: true },
  { title: 'Advanced Exterior Visualization with Rhino', slug: 'advanced-exterior-visualization-rhino', short_description: 'Create stunning exterior visualizations from Rhino models.', description: 'Advanced visualization techniques for Rhino.', level: 'advanced', duration_hours: 14, total_lessons: 35, price_usd: 79, price_inr: 6499, is_featured: false, is_published: true },
  { title: 'Rhino 7: Complete 3D Modeling for Architecture', slug: 'rhino-7-complete-3d-modeling-architecture', short_description: 'Master Rhino for architectural modeling and design.', description: 'Learn Rhino 3D for architecture.', level: 'beginner', duration_hours: 22, total_lessons: 55, price_usd: 99, price_inr: 8499, is_featured: true, is_published: true },
  { title: 'Grasshopper Parametric Design: From Zero to Hero', slug: 'grasshopper-parametric-design-zero-hero', short_description: 'Master parametric design with Grasshopper in Rhino.', description: 'Learn algorithmic design with Grasshopper.', level: 'intermediate', duration_hours: 18, total_lessons: 45, price_usd: 109, price_inr: 9499, is_featured: false, is_published: true },
  { title: 'V-Ray for Rhino: Advanced Rendering Techniques', slug: 'vray-rhino-advanced-rendering-techniques', short_description: 'Create stunning renders with V-Ray for Rhino.', description: 'Master V-Ray rendering in Rhino.', level: 'advanced', duration_hours: 12, total_lessons: 30, price_usd: 89, price_inr: 7499, is_featured: false, is_published: true },
  
  // Design Fundamentals
  { title: 'Architectural Drawing: From Imagination to Conceptualization', slug: 'architectural-drawing-imagination-conceptualization', short_description: 'Transform ideas into compelling architectural drawings.', description: 'Bridge the gap between imagination and paper.', level: 'beginner', duration_hours: 12, total_lessons: 30, price_usd: 59, price_inr: 4999, is_featured: false, is_published: true },
  { title: 'Architectural Design Fundamentals', slug: 'architectural-design-fundamentals', short_description: 'Core principles of architectural design.', description: 'Understand the principles of great architecture.', level: 'beginner', duration_hours: 14, total_lessons: 35, price_usd: 69, price_inr: 5999, is_featured: false, is_published: true },
  { title: 'Architectural Sketching: Thinking with Pen and Paper', slug: 'architectural-sketching-thinking-pen-paper', short_description: 'Master the art of architectural hand sketching.', description: 'Develop your visual thinking skills through sketching.', level: 'beginner', duration_hours: 10, total_lessons: 25, price_usd: 49, price_inr: 3999, is_featured: true, is_published: true },
  { title: 'Introduction to Architectural Sketching', slug: 'introduction-architectural-sketching', short_description: 'Begin your architectural sketching journey.', description: 'Start sketching with confidence.', level: 'beginner', duration_hours: 6, total_lessons: 15, price_usd: 39, price_inr: 2999, is_featured: false, is_published: true },
  { title: 'Architectural English for Design Students and Professionals', slug: 'architectural-english-design-students-professionals', short_description: 'Master architectural terminology and communication.', description: 'Communicate like a design professional.', level: 'beginner', duration_hours: 8, total_lessons: 20, price_usd: 49, price_inr: 3999, is_featured: false, is_published: true },
  { title: 'Create a Professional Architectural Portfolio with Adobe InDesign', slug: 'professional-architectural-portfolio-indesign', short_description: 'Design a stunning portfolio that lands you jobs.', description: 'Your portfolio is your ticket to opportunities.', level: 'intermediate', duration_hours: 10, total_lessons: 25, price_usd: 59, price_inr: 4999, is_featured: true, is_published: true },
  { title: 'The Complete Interior Design Course', slug: 'complete-interior-design-course', short_description: 'Everything you need to start your interior design career.', description: 'A comprehensive journey through interior design.', level: 'beginner', duration_hours: 32, total_lessons: 80, price_usd: 129, price_inr: 10999, is_featured: true, is_published: true },
  { title: 'Architectural Diagrams Masterclass', slug: 'architectural-diagrams-masterclass', short_description: 'Create compelling architectural diagrams that tell stories.', description: 'Diagrams are essential for design communication.', level: 'intermediate', duration_hours: 8, total_lessons: 20, price_usd: 59, price_inr: 4999, is_featured: false, is_published: true },
  { title: 'Architectural Materials Masterclass', slug: 'architectural-materials-masterclass', short_description: 'Deep dive into materials for architectural design.', description: 'Understand materials at a fundamental level.', level: 'intermediate', duration_hours: 12, total_lessons: 30, price_usd: 69, price_inr: 5999, is_featured: false, is_published: true },
  { title: 'Introduction to Architectural Design of Residential Spaces', slug: 'intro-architectural-design-residential-spaces', short_description: 'Learn the fundamentals of residential architecture.', description: 'Start designing homes with confidence.', level: 'beginner', duration_hours: 14, total_lessons: 35, price_usd: 69, price_inr: 5999, is_featured: false, is_published: true },
  { title: 'Complete Guide to Construction Engineering and Management', slug: 'complete-guide-construction-engineering-management', short_description: 'Master construction project management and engineering.', description: 'Essential knowledge for construction professionals.', level: 'intermediate', duration_hours: 24, total_lessons: 60, price_usd: 99, price_inr: 8499, is_featured: false, is_published: true },
  { title: 'Master Planner Program Pro', slug: 'master-planner-program-pro', short_description: 'Become a master at planning architectural projects.', description: 'Strategic planning for project success.', level: 'advanced', duration_hours: 20, total_lessons: 50, price_usd: 119, price_inr: 9999, is_featured: false, is_published: true },
  { title: 'Concept Sketching for Architecture and Design', slug: 'concept-sketching-architecture-design', short_description: 'Master rapid concept visualization techniques.', description: 'Learn to sketch concepts quickly and effectively.', level: 'beginner', duration_hours: 8, total_lessons: 20, price_usd: 49, price_inr: 3999, is_featured: false, is_published: true },
  { title: 'Foundation Sketching: Architectural Design Part 1', slug: 'foundation-sketching-architectural-design-part1', short_description: 'Build strong sketching foundations for architectural design.', description: 'The first step to becoming a confident sketcher.', level: 'beginner', duration_hours: 10, total_lessons: 25, price_usd: 49, price_inr: 3999, is_featured: false, is_published: true },
  { title: 'Frank Gehry Teaches Design and Architecture', slug: 'frank-gehry-teaches-design-architecture', short_description: 'Learn from one of architectures greatest masters.', description: 'A rare opportunity to learn directly from Frank Gehry.', level: 'intermediate', duration_hours: 6, total_lessons: 15, price_usd: 89, price_inr: 7499, is_featured: true, is_published: true },
  { title: 'Introduction to Marker Rendering for Architecture and Interiors', slug: 'introduction-marker-rendering-architecture-interiors', short_description: 'Create stunning hand-rendered presentations with markers.', description: 'Master the art of marker rendering.', level: 'beginner', duration_hours: 10, total_lessons: 25, price_usd: 59, price_inr: 4999, is_featured: false, is_published: true },
  { title: 'Architectural Sketching: Hand Drawing Fundamentals', slug: 'architectural-sketching-hand-drawing-fundamentals', short_description: 'Master hand sketching for architectural communication.', description: 'Learn essential hand drawing skills.', level: 'beginner', duration_hours: 14, total_lessons: 35, price_usd: 59, price_inr: 4999, is_featured: false, is_published: true },
  { title: 'Design Portfolio Masterclass: Stand Out & Get Hired', slug: 'design-portfolio-masterclass-stand-out-get-hired', short_description: 'Create a portfolio that gets you noticed.', description: 'Build an impressive design portfolio.', level: 'intermediate', duration_hours: 8, total_lessons: 20, price_usd: 49, price_inr: 3999, is_featured: false, is_published: true },
  { title: 'Color Theory & Application in Architecture', slug: 'color-theory-application-architecture', short_description: 'Master color for architectural design and visualization.', description: 'Learn color theory for architects.', level: 'beginner', duration_hours: 6, total_lessons: 15, price_usd: 39, price_inr: 2999, is_featured: false, is_published: true },
  
  // Interior Design
  { title: 'Complete Interior Design Course: Concept to Completion', slug: 'complete-interior-design-concept-completion', short_description: 'Full interior design workflow from concept to final presentation.', description: 'Master the complete interior design process.', level: 'beginner', duration_hours: 30, total_lessons: 75, price_usd: 129, price_inr: 10999, is_featured: true, is_published: true },
  { title: 'Space Planning & Furniture Layout Principles', slug: 'space-planning-furniture-layout-principles', short_description: 'Master the art of space planning and furniture arrangement.', description: 'Learn professional space planning techniques.', level: 'intermediate', duration_hours: 10, total_lessons: 25, price_usd: 59, price_inr: 4999, is_featured: false, is_published: true },
  { title: 'Residential Interior Design: Modern Living Spaces', slug: 'residential-interior-design-modern-living-spaces', short_description: 'Design stunning modern residential interiors.', description: 'Learn to design beautiful modern homes.', level: 'intermediate', duration_hours: 18, total_lessons: 45, price_usd: 89, price_inr: 7499, is_featured: false, is_published: true },
  { title: 'Commercial Interior Design: Offices & Retail Spaces', slug: 'commercial-interior-design-offices-retail-spaces', short_description: 'Master commercial interior design for offices and retail.', description: 'Learn commercial interior design.', level: 'advanced', duration_hours: 20, total_lessons: 50, price_usd: 99, price_inr: 8499, is_featured: false, is_published: true },
  { title: 'Interior Design for Your Dream Living Room - Simple & Fast', slug: 'interior-design-dream-living-room', short_description: 'Design the perfect living room quickly and easily.', description: 'Transform your living room with professional design.', level: 'beginner', duration_hours: 6, total_lessons: 15, price_usd: 39, price_inr: 2999, is_featured: false, is_published: true },
  { title: 'Interior Design Fundamentals 2026: Beginner to Advanced', slug: 'interior-design-fundamentals-2026-beginner-advanced', short_description: 'Latest trends and timeless principles for 2026.', description: 'Stay current with the latest in interior design.', level: 'beginner', duration_hours: 22, total_lessons: 55, price_usd: 99, price_inr: 8499, is_featured: true, is_published: true },
  
  // Post-Production
  { title: 'Photoshop for Architects: From Zero to Advanced Masterclass', slug: 'photoshop-architects-zero-advanced-masterclass', short_description: 'Master Photoshop for architectural visualization and presentation.', description: 'Essential Photoshop skills for architects.', level: 'beginner', duration_hours: 20, total_lessons: 50, price_usd: 89, price_inr: 7499, is_featured: true, is_published: true },
  { title: 'Photoshop Architectural Post-Production and Presentation', slug: 'photoshop-architectural-post-production-presentation', short_description: 'Transform renders into stunning presentations.', description: 'Professional post-production techniques.', level: 'intermediate', duration_hours: 14, total_lessons: 35, price_usd: 79, price_inr: 6499, is_featured: false, is_published: true },
  { title: 'Photoshop Architectural Visualization in 1 Hour: Mini Course', slug: 'photoshop-architectural-visualization-1-hour', short_description: 'Quick Photoshop skills for immediate results.', description: 'Learn essential Photoshop in just one hour.', level: 'beginner', duration_hours: 1, total_lessons: 5, price_usd: 19, price_inr: 1499, is_featured: false, is_published: true },
  { title: 'Architectural Drawing: From Paper to Photoshop', slug: 'architectural-drawing-paper-photoshop', short_description: 'Bridge traditional drawing with digital enhancement.', description: 'Combine hand drawings with digital enhancement.', level: 'intermediate', duration_hours: 12, total_lessons: 30, price_usd: 69, price_inr: 5999, is_featured: false, is_published: true },
  { title: 'Architectural Presentation: After Effects for Architects', slug: 'architectural-presentation-after-effects-architects', short_description: 'Create dynamic animated presentations with After Effects.', description: 'Bring your presentations to life with motion graphics.', level: 'intermediate', duration_hours: 16, total_lessons: 40, price_usd: 89, price_inr: 7499, is_featured: true, is_published: true },
  { title: 'Photoshop for Architects: Post-Production Mastery', slug: 'photoshop-architects-post-production-mastery', short_description: 'Master Photoshop for architectural visualization post-production.', description: 'Learn Photoshop techniques for architects.', level: 'intermediate', duration_hours: 14, total_lessons: 35, price_usd: 69, price_inr: 5999, is_featured: true, is_published: true },
  { title: 'After Effects for Arch Viz: Animation & Motion Graphics', slug: 'after-effects-arch-viz-animation-motion-graphics', short_description: 'Create stunning motion graphics for architectural presentations.', description: 'Master After Effects for architecture.', level: 'intermediate', duration_hours: 16, total_lessons: 40, price_usd: 79, price_inr: 6499, is_featured: false, is_published: true },
  { title: 'Presentation Skills for Architects and Designers', slug: 'presentation-skills-architects-designers', short_description: 'Present your designs with confidence and impact.', description: 'Master presentation techniques.', level: 'beginner', duration_hours: 6, total_lessons: 15, price_usd: 39, price_inr: 2999, is_featured: false, is_published: true },
];

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    let synced = 0;
    let skipped = 0;

    for (const course of staticCourses) {
      // Check if course already exists
      const { data: existing } = await supabase
        .from("courses")
        .select("id")
        .eq("slug", course.slug)
        .single();

      if (existing) {
        skipped++;
        continue;
      }

      // Insert new course
      const { error } = await supabase.from("courses").insert({
        title: course.title,
        slug: course.slug,
        short_description: course.short_description,
        description: course.description,
        level: course.level,
        duration_hours: course.duration_hours,
        total_lessons: course.total_lessons,
        price_usd: course.price_usd,
        price_inr: course.price_inr,
        is_featured: course.is_featured,
        is_published: course.is_published,
      });

      if (!error) {
        synced++;
      } else {
        console.error("Error inserting course:", course.slug, error);
      }
    }

    return new Response(
      JSON.stringify({ success: true, synced, skipped, total: staticCourses.length }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("Error:", error);
    const errorMessage = error instanceof Error ? error.message : "Unknown error";
    return new Response(
      JSON.stringify({ success: false, error: errorMessage }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
